baseURL = "https://sumit-mundra.github.io"
languageCode = "en-us"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Resume"
  URL = "/resume"
  weight = 4

  [[menu.header]]
  name = "Experience"
  URL = "#experience"
  weight = 3

  [[menu.header]]
  name = "Blog"
  URL = "/blog"
  weight = 5

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 6

  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Resume"
  URL = "/resume"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4


[params]

  sections = ["showcase", "about", "education", "experience", "contact"]

  homepageExperienceCount = 1

  [params.analytics.google_tag_manager]
      id = "G-RZBM5YX7LD"
      enabled = true
  
  [params.logo]
    text1 = "Sumit"
    text2 = "Mundra"

  [params.footer]
    copyright = ""
  [params.footer.radity_logo]
    x = "img/general/design-and-code-radity.png"
    _2x = "img/general/design-and-code-radity@2x.png"
    alt = "Design & Code - Radity"